apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-frontend
  template:
    metadata:
      labels:
        app: pod-frontend
    spec:
      containers:
        - name: container-frontend
          image: docker.io/library/frontend:v3
          ports:
            - name: frontend 
              containerPort: 80

