apiVersion: v1
kind: Service
metadata:
  name: service-wk-frontend
spec:
  type: NodePort 
  # type: ClusterIP 
  selector:
    app: pod-wk-frontend
  ports:
    - name: listeners
      port: 9998 
      targetPort: frontend 
