apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-backend
  template:
    metadata:
      labels:
        app: pod-backend
    spec:
      containers:
        - name: container-backend
          image: docker.io/library/backend:v1
          ports:
            - name: backend 
              containerPort: 80

